# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

dynsbmcore <- function(T, N, Q, Yasvector, present, edgetype, K, clustering, nbit = 20L, nbthreads = 1L, isdirected = FALSE, withselfloop = FALSE) {
    .Call('dynsbm_dynsbmcore', PACKAGE = 'dynsbm', T, N, Q, Yasvector, present, edgetype, K, clustering, nbit, nbthreads, isdirected, withselfloop)
}

